baseURL = "/"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
# googleAnalytics = "UA-123-s45"
languageCode = "en-AU"
title = "Hugo Boilerplate"

[params]
  description = ""
  facebook = ""
  language = "en-AU"
  name = ""
  twitterCreator = ""
  twitterSite = ""
  url = ""

[frontmatter]
  date  = [":filename", ":default"]

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[permalinks]
  post = "/:slug/"

[outputs]
  home = ["HTML"]
  section = ["HTML"]

# For sites that have and RSS and/or JSON feed, uncomment this section, delete the [outputs] section above and remove "RSS" from "disableKinds"
# [outputs]
#   home = ["HTML", "RSS", "JSON"]
#   section = ["HTML"]

# [outputFormats.RSS]
#   mediatype = "application/rss"
#   baseName = "feed"

# [outputFormats.JSON]
#   mediatype = "application/json"
#   baseName = "feed"