baseurl           = "https://reportplumbing.com.au"
disableKinds      = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode      = "en-AU"
title             = "Report Plumbing"

[params]
  siteDescription = "We cover all aspects of plumbing, home maintenance and water filtration systems. Prompt reliable and personal service in the Port Maquarie area."
  phone           = "1800 421 241"
  email           = "reportplumbing@bigpond.com"
  facebook        = ""
  twitter         = ""
