baseURL = "/"
disableKinds = ["taxonomy", "taxonomyTerm"]
# googleAnalytics = "UA-123-s45"
languageCode = "en-AU"
pygmentsCodeFences = true
# PygmentsStyle = "paraiso-light"
pygmentsUseClasses = true
title = "Hugo Boilerplate"

[params]
  description = "Luke Bennett's Blog"
  language = "en-AU"
  name = "Luke Bennett"
  twitterCreator = "@luke_bennett_"
  twitterSite = "@luke_bennett_"
  url = "https://lukebennett.me/"

[frontmatter]
  date  = [":filename", ":default"]

[menu]
  [[menu.main]]
    name = "Posts"
    url  = "/post/"
    weight = 1
  [[menu.main]]
    name = "Archive"
    url  = "/archive/"
    weight = 2

[permalinks]
  post = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  baseName = "feed"
  mediatype = "application/rss"

[outputFormats.JSON]
  baseName = "feed"
  mediatype = "application/json"
