baseurl           = ""
disableKinds      = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode      = "en-AU"
title             = "Report Plumbing"

[params]
  siteDescription = "A boilerplate Hugo site to get you up and running quickly"
  phone           = ""
  email           = ""
  facebook        = ""
  twitter         = "@luke_bennett_"
