baseURL = "/"
title = "Luke Bennett"
# theme = "hugo-boilerplate-theme"
languageCode = "en-AU"
# googleAnalytics = "UA-123-s45"
disableKinds = ["taxonomy", "taxonomyTerm"]
pygmentsCodeFences = true
pygmentsUseClasses = true
# PygmentsStyle = "paraiso-light"

[params]
  description = "Luke Bennett's Blog"
  language = "en-AU"
  name = "Luke Bennett"
  twitterSite = "@luke_bennett_"
  twitterCreator = "@luke_bennett_"

[frontmatter]
  date  = [":filename", ":default"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Posts"
    url  = "/post/"
    weight = 1
  [[menu.main]]
    name = "Archive"
    url  = "/archive/"
    weight = 2

[permalinks]
  post = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"