baseurl           = "/"
disableKinds      = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode      = "en-AU"
title             = "Hugo Boilerplate"

[params]
  siteDescription = ""
  phone           = ""
  email           = ""
  facebook        = ""
  twitter         = ""
