baseurl           = "https://hugo-starter.netlify.com"
disableKinds      = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode      = "en-AU"
title             = "Hugo Boilerplate"

[params]
  siteDescription = "A boilerplate Hugo site to get you up and running quickly"
  phone           = ""
  email           = ""
  facebook        = ""
  twitter         = "@luke_bennett_"
