name = "hugo-boilerplate"
license = "MIT"
licenselink = "https://github.com/lukebennett88/hugo-boilerplate/blob/master/LICENSE"
description = "Basic boilerplate/theme to get a Hugo site up and running quickly"
homepage = "https://github.com/lukebennett88/hugo-boilerplate"
tags = []
features = []
min_version = "0.45"

[author]
  name = "Luke Bennett"
  homepage = "https://lukebennett.me"